version: "3.8"

services:
    fairify:
        restart: always
        build: ./fairify
        image: fairify
        container_name: fairify
        command: flask run
        environment:      
            - FLASK_APP=app.py
            - FLASK_RUN_HOST=0.0.0.0
            - FLASK_RUN_PORT=5000
            - FLASK_DEBUG=1
            - BINARY_LABEL_METRIC_API=${BINARY_LABEL_METRIC_API}
        expose:
            - 5000
    nginx:
        restart: always
        build: ./nginx
        image: nginx
        container_name: nginx-fairify
        ports:
            - 8081:8081
        depends_on:
            - fairify